#Bootstrap: docker
#From: ubuntu:22.04
#nvcr.io/nvidia/nvhpc:25.11-devel-cuda_multi-ubuntu22.04
#nvcr.io/nvidia/nvhpc:26.1-devel-cuda_multi-ubuntu22.04
#From: nvcr.io/nvidia/nvhpc:24.11-devel-cuda_multi-ubuntu22.04
Bootstrap: localimage
From: ubuntu_jammy.sif
Stage: spython-base

%post
# Start from NVIDIA CUDA base image

# Set environment variables
DEBIAN_FRONTEND=noninteractive
QE_VERSION="7.4.1"
%setup
    ls -la  ${GITHUB_WORKSPACE} \
&&     export CACHEDIR=${GITHUB_WORKSPACE}/../../../cache\
&&     bash -c "if [[  -f ${CACHEDIR}/ompi/lib/libmpi.so ]]; then mkdir -p ${SINGULARITY_ROOTFS}/opt ;rsync -a ${CACHEDIR}/ompi ${SINGULARITY_ROOTFS}/opt/. ; echo ompi/ucx cache fetched ;fi"

%post
# Install required packages
apt-get update && apt-get install -y \
build-essential \
wget \
git \
python3 \
python3-pip \
gfortran \
pkg-config \
make \
cmake \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

# Create working directory
mkdir -p /build
cd /build

#build ompi ucx
export ompi_options=' --enable-mca-no-build=coll-han '
 apt-get -y update \
&& apt-get -y install -y tzdata git moreutils  wget rsync  sudo ca-certificates \
&& apt-get -y install -y   tar libnl-3-200 libnl-route-3-200 libgomp1 libnuma1 \
 g++ gfortran   make ssh patch   unzip perl-base file \
 python3 python3-dev cmake  unzip zip perl automake libtool autoconf flex  \
 libnuma-dev libslurm-dev \
 libnl-3-dev  libnl-route-3-dev udev \
 librdmacm-dev librdmacm1 rdma-core libibverbs-dev  ibverbs-providers  \
 libhwloc-dev libfuse3-dev\
 pkg-config gawk  software-properties-common strace gdb \
 	    && nv_year=2025 && nv_major=25 &&  nv_minor=11 &&   nverdot="$nv_major"."$nv_minor" && nverdash="$nv_major"-"$nv_minor" \
	    &&  apt-get install -q=2 -y --no-install-recommends g++ libtinfo5  libncursesw5 libnuma1 ; wget  --progress=dot:giga https://developer.download.nvidia.com/hpc-sdk/ubuntu/"$arch_dpkg/"nvhpc-"$nverdash"_"$nverdot"_$arch_dpkg.deb >& log1 ; wget --progress=dot:giga  https://developer.download.nvidia.com/hpc-sdk/ubuntu/$arch_dpkg/nvhpc-"$nv_year"_"$nverdot"_"$arch_dpkg".deb >&  log2 ; tail -n 2 log1 log2; ls -lrt nv*deb;  dpkg -i nvhpc*deb ; 	 /opt/nvidia/hpc_sdk/Linux_"$arch"/"$nverdot"/compilers/bin/makelocalrc -x  ;   rm -f nvhpc*deb ; mkdir -p /opt/lib || true;  \
	    rsync -a /opt/nvidia/hpc_sdk/Linux_"$arch"/"$nverdot"/compilers/lib/*.so* /opt/lib/.;  \
	    rsync -a /opt/nvidia/hpc_sdk/Linux_"$arch"/"$nverdot"/math_libs/*/lib64/*.so* /opt/lib/. ; \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/* \
&& export FC=nvfortran && export OMPI=5.0.9 &&export OMPI_DIR=/opt/ompi && export UCX=1.20.0 \
&& export CUDA_ROOT=/opt/nvidia/hpc_sdk/Linux_x86_64/25.11/cuda/13.0/targets/x86_64-linux/ \
            &&  export PATH=/opt/nvidia/hpc_sdk/Linux_"$arch"/"$nverdot"/compilers/bin:"$PATH" \
            &&  export LD_LIBRARY_PATH=/opt/nvidia/hpc_sdk/Linux_"$arch"/"$nverdot"/compilers/lib:"$LD_LIBRARY_PATH" \
	    && echo 'FC -v ' $("$FC" -v) \
	    && rm -f nvcc.out && nvcc -V >& nvcc.out && cat nvcc.out && rm nvcc.out \
&& export ompi_prefix=openmpi-$OMPI\
&& export ompi_major=$(echo $OMPI | cut -d . -f1) \
&& echo ompi_major is $ompi_major \
&& export ompi_minor=$(echo $OMPI | cut -d . -f2) \
&& echo ompi_minor is $ompi_minor \
&& echo ompi_major is $ompi_major \
&& wget --progress=dot:giga  https://github.com/openucx/ucx/releases/download/v$UCX/ucx-$UCX.tar.gz -O - | tar xzf - \
&& wget  --progress=dot:giga https://download.open-mpi.org/release/open-mpi/v$ompi_major.$ompi_minor/openmpi-$OMPI.tar.gz  -O - | tar xzf -   \
&& cd ucx-$UCX \
&& wget https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi41x.ifx/ucx_malloc.patch \
&& wget https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi5x/ucx1181_malloc.patch \
&& if [[ $UCX == 1.14.1 ]] || [[ $UCX == 1.15.0 ]]; then patch -p0 < ./ucx_malloc.patch ; else patch -p0 < ./ucx1181_malloc.patch; fi \
&& mkdir build && cd build \
&& ../configure --prefix=$OMPI_DIR --disable-logging --disable-debug --disable-assertions --disable-params-check  \
 --enable-mt --without-cuda \
&& make -j4 && make install \
&& if [ ! -f $OMPI_DIR/bin/ucx_info ]; then echo ucx_info\ not\ found ; exit 1 ; fi  

cd ../.. \
&& cd $ompi_prefix     \
&& export CC=nvc \
&& ./configure  --prefix=$OMPI_DIR --with-ucx=$OMPI_DIR --enable-mca-no-build=btl-uct   \
$ompi_options \
--enable-mpi1-compatibility --with-slurm --without-tm --without-lsf  \
 --without-sge --without-alps --without-lustre --disable-memchecker \
 --without-hcoll --disable-static  \
 --disable-mpi-java --enable-dlopen --with-cuda=$CUDA_ROOT  \
 --without-munge \
  FC=$FC  \
&& head config.log \
&& make FC=$FC  -j 6 \
&& make install     \
&& if [ ! -f $OMPI_DIR/bin/mpif90 ]; then echo mpif90\ not\ found ; exit 1 ; fi \
&& echo mpif90 show is $($OMPI_DIR/bin/mpif90 -show) \
&& cd .. ; rm -rf *tar*gz openmpi-* ucx-*  \
&& echo ' check ucx' \
&& if [ ! -f $OMPI_DIR//bin/ucx_info ]; then echo ucx_info\ not\ found ; exit 1 ; fi \
&& echo ' /opt/ompi/bin/ucx_info -v ' `/opt/ompi/bin/ucx_info -v|| true` \
&& echo ' ucx Transports' `/opt/ompi/bin/ucx_info  -d |grep Transport |cut -c 19- || true` \
&& if [ ! -f $OMPI_DIR/bin/mpif90 ]; then echo mpif90\ not\ found ; exit 1 ; fi \
&& echo '********'  \
&& export PATH=$OMPI_DIR/bin:$PATH\
&& export LD_LIBRARY_PATH=$OMPI_DIR/lib:$LD_LIBRARY_PATH 

# Download and extract Quantum ESPRESSO
wget https://github.com/QEF/q-e/archive/qe-${QE_VERSION}.tar.gz \
&& tar -xzf qe-${QE_VERSION}.tar.gz \
&& rm qe-${QE_VERSION}.tar.gz

mkdir -p /build
cd /build
# Configure and build Quantum ESPRESSO with GPU support using NVHPC
mkdir -p /build/q-e-qe-${QE_VERSION}
cd /build/q-e-qe-${QE_VERSION}
export CC=pgcc
# Configure with NVHPC compiler
./configure \
--enable-openmp \
--enable-parallel \
--with-scalapack=yes \
--with-cuda=yes \
--with-cuda-cc=90 \
--with-cuda-runtime=13.0 \
--with-cuda-mpi=yes \
&& make pw -j$(nproc) \
&& make cp -j$(nproc) \
&& make ph -j$(nproc) \
&& make pp -j$(nproc) \
&& make install

# # Set working directory for running calculations
mkdir -p /work
cd /work
#cleanup
rm -rf $(find /opt/nvidia/hpc_sdk/Linux_x86_64 -name 12.9)
# # Add environment setup script
# RUN echo '#!/bin/bash\n\
# export CUDA_VISIBLE_DEVICES=${GPU_ID:-0}\n\
# export OMP_NUM_THREADS=${OMP_NUM_THREADS:-1}\n\
# export LD_LIBRARY_PATH="/opt/nvidia/hpc_sdk/Linux_x86_64/24.1/compilers/lib:${LD_LIBRARY_PATH}"\n\
# exec "$@"' > /entrypoint.sh \
#     && chmod +x /entrypoint.sh

# ENTRYPOINT ["/entrypoint.sh"]
# CMD ["pw.x"]
%environment
export DEBIAN_FRONTEND=noninteractive
export QE_VERSION="7.4"
%runscript
cd /work
exec /bin/bash "$@"
%startscript
cd /work
exec /bin/bash "$@"
